import { SHOW_SOCIAL_PROOF } from "@/lib/constants";
import { TESTIMONIALS_DATA } from "@/data/testimonials";
import { BUILT_WITH_GALLERY_DATA } from "@/data/built-with";
import { STATS_DATA } from "@/data/stats";
import { Quote, Sparkles } from "lucide-react";

export function SocialProofSection() {
  // Gated behind SHOW_SOCIAL_PROOF (default false) to avoid showing placeholder content in production
  if (!SHOW_SOCIAL_PROOF) {
    return null;
  }

  // Filter stats that have non-empty, valid values
  const visibleStats = STATS_DATA.filter(
    (stat) => stat.value && stat.value.trim().length > 0
  );

  return (
    <section
      id="social-proof"
      aria-label="Community proof and showcase"
      className="py-16 sm:py-24 bg-ink border-t border-slate-line scroll-mt-24"
    >
      <div className="max-w-[1180px] mx-auto px-5 sm:px-8">
        {/* Optional Stats Strip (auto-hidden if all stats are null or empty) */}
        {visibleStats.length > 0 && (
          <div className="mb-20 grid grid-cols-1 sm:grid-cols-3 gap-6 border border-slate-line bg-ink-raised/40 rounded-lg p-6 sm:p-8 text-center">
            {visibleStats.map((stat) => (
              <div key={stat.id} className="space-y-1">
                <span className="font-serif text-3xl sm:text-4xl text-amber font-normal">
                  {stat.value}
                </span>
                <p className="font-mono text-xs uppercase tracking-wider text-cream font-medium">
                  {stat.label}
                </p>
                {stat.description && (
                  <p className="text-xs text-fog-dim">{stat.description}</p>
                )}
              </div>
            ))}
          </div>
        )}

        {/* Part A: Testimonials Row (3 Cards) */}
        <div className="mb-20">
          <div className="max-w-[640px] mb-10">
            <span className="font-mono text-xs uppercase tracking-wider text-amber font-medium block mb-2">
              Feedback from Builders
            </span>
            <h2 className="font-serif font-normal text-2xl sm:text-3xl lg:text-4xl text-cream leading-[1.15]">
              Trusted by creators moving from prompt to code
            </h2>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            {TESTIMONIALS_DATA.map((t) => (
              <div
                key={t.id}
                className="rounded-lg border border-slate-line bg-ink-raised/50 p-6 flex flex-col justify-between"
              >
                <div>
                  <Quote className="size-5 text-amber/60 mb-4" />
                  <p className="text-sm text-fog leading-relaxed font-sans italic">
                    &ldquo;{t.quote}&rdquo;
                  </p>
                </div>
                <div className="mt-6 pt-4 border-t border-slate-line/50 flex items-center gap-3">
                  <div className="size-9 rounded-full bg-slate-line flex items-center justify-center font-mono text-xs font-semibold text-amber">
                    {t.name.charAt(1) || "U"}
                  </div>
                  <div>
                    <span className="block text-xs font-medium text-cream">
                      {t.name}
                    </span>
                    <span className="block text-[11px] text-fog-dim font-mono">
                      {t.role} {t.company ? `· ${t.company}` : ""}
                    </span>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Part B: Built with Klyro Gallery Grid (6 Cards) */}
        <div>
          <div className="max-w-[640px] mb-10">
            <span className="font-mono text-xs uppercase tracking-wider text-amber font-medium block mb-2">
              Gallery Grid
            </span>
            <h2 className="font-serif font-normal text-2xl sm:text-3xl lg:text-4xl text-cream leading-[1.15]">
              Built with Klyro
            </h2>
            <p className="mt-2 text-xs sm:text-sm text-fog leading-relaxed">
              Explore responsive applications and tools generated by our community.
            </p>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
            {BUILT_WITH_GALLERY_DATA.map((item) => (
              <div
                key={item.id}
                className="group rounded-lg border border-slate-line bg-ink-raised/40 overflow-hidden hover:border-slate-line/80 transition-colors"
              >
                {/* Mockup / Screenshot placeholder container */}
                <div className="h-44 bg-ink border-b border-slate-line/60 flex items-center justify-center p-4 text-center relative overflow-hidden">
                  <div className="absolute inset-0 bg-gradient-to-t from-ink via-transparent to-transparent opacity-60" />
                  <div className="space-y-1 relative z-10">
                    <Sparkles className="size-5 text-amber/60 mx-auto" />
                    <span className="font-mono text-xs text-fog-dim block">
                      {item.category}
                    </span>
                    <span className="font-serif text-sm text-cream font-medium">
                      {item.title}
                    </span>
                  </div>
                </div>

                {/* Prompt Card Footer */}
                <div className="p-4 space-y-2">
                  <span className="font-mono text-[10px] uppercase tracking-wider text-amber block">
                    Original Prompt
                  </span>
                  <p className="font-mono text-xs text-fog leading-snug line-clamp-2">
                    &ldquo;{item.prompt}&rdquo;
                  </p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </section>
  );
}
