/* REVIEW WITH LEGAL COUNSEL: The following Terms of Service document is a draft template provided for platform operation and must be reviewed and customized by qualified legal counsel prior to enterprise deployment. */

import React from "react";
import type { Metadata } from "next";
import Link from "next/link";
import { Navbar } from "@/components/landing/Navbar";
import { Footer } from "@/components/landing/Footer";
import { CONTACT_EMAIL } from "@/lib/constants";

export const metadata: Metadata = {
  title: "Klyro Terms of Service",
  description:
    "Review the terms, acceptable use standards, and generated code ownership agreements governing your use of Klyro.",
};

export default function TermsPage() {
  return (
    <div className="flex min-h-dvh flex-col bg-ink text-cream font-sans antialiased overflow-x-hidden selection:bg-amber selection:text-[#201404]">
      <Navbar />

      <main className="flex-1 py-12 sm:py-20">
        <div className="mx-auto w-full max-w-[820px] px-5 sm:px-8">
          {/* Header Block */}
          <header className="border-b border-slate-line pb-8">
            <span className="font-mono text-xs font-medium uppercase tracking-widest text-amber">
              Legal &amp; Compliance
            </span>
            <h1 className="mt-3 font-serif text-3xl font-normal tracking-tight text-cream sm:text-5xl">
              Terms of Service
            </h1>
            <p className="mt-4 font-mono text-xs text-fog-dim">
              Last updated: September 20, 2026
            </p>
            <p className="mt-4 text-sm sm:text-base leading-relaxed text-fog">
              Please read these Terms of Service carefully before creating an account or generating applications on Klyro.
            </p>
          </header>

          {/* Terms Content Body */}
          <div className="mt-10 space-y-10 text-xs sm:text-sm leading-relaxed text-fog">
            {/* 1. Acceptance */}
            <section className="space-y-2.5">
              <h2 className="font-serif text-lg sm:text-xl font-medium text-cream">
                1. Acceptance of Terms
              </h2>
              <p>
                By creating an account, accessing, or using Klyro (&ldquo;we&rdquo;, &ldquo;us&rdquo;, or &ldquo;our&rdquo;), you agree to be bound by these Terms of Service and all policies referenced herein. If you are entering into these terms on behalf of an entity, you represent that you possess the authority to bind that entity.
              </p>
            </section>

            {/* 2. Platform Description */}
            <section className="space-y-2.5">
              <h2 className="font-serif text-lg sm:text-xl font-medium text-cream">
                2. Platform Scope and Service
              </h2>
              <p>
                Klyro provides an AI-assisted software generation service that synthesizes front-end web applications (specifically React, Next.js, and Tailwind CSS components) from natural language instructions. You acknowledge that Klyro produces front-end source code and interactive prototypes; you are responsible for connecting back-end databases, authentication providers, and hosting infrastructure when deploying generated software to production environments.
              </p>
            </section>

            {/* 3. Code Ownership */}
            <section className="space-y-2.5 rounded-md border border-amber/30 bg-amber/[0.04] p-5 sm:p-6">
              <h2 className="font-serif text-lg sm:text-xl font-medium text-amber">
                3. Generated Code Ownership &amp; Export Rights
              </h2>
              <p className="text-cream">
                <strong>You own your code:</strong> To the maximum extent permitted by applicable law, you retain all right, title, and interest in and to the source code files, page structures, styling, and visual layouts generated by Klyro in response to your prompts.
              </p>
              <p>
                You are free to export, modify, compile, host, distribute, license, or sell applications generated using Klyro for commercial or non-commercial purposes without payment of royalties or attribution to Klyro. Klyro claims no intellectual property ownership over your exported source code.
              </p>
            </section>

            {/* 4. Accounts & Fair Use */}
            <section className="space-y-2.5">
              <h2 className="font-serif text-lg sm:text-xl font-medium text-cream">
                4. Account Responsibilities &amp; Fair Use
              </h2>
              <p>
                You are responsible for maintaining the confidentiality of your login credentials and for all activities that occur under your account.
              </p>
              <p>
                For plans offering unlimited generations, usage is subject to standard fair-use policies. We reserve the right to throttle or suspend accounts that use automated scraping tools, high-frequency scripting bots, or excessive compute loads that degrade platform availability for other users.
              </p>
            </section>

            {/* 5. Acceptable Use */}
            <section className="space-y-2.5">
              <h2 className="font-serif text-lg sm:text-xl font-medium text-cream">
                5. Acceptable Use Standards
              </h2>
              <p>
                You agree not to use Klyro to generate software designed to engage in malicious activities, including but not limited to: phishing, credential harvesting, malware distribution, harassment, impersonation, or unauthorized access to computer systems.
              </p>
            </section>

            {/* 6. Subscriptions & Billing */}
            <section className="space-y-2.5">
              <h2 className="font-serif text-lg sm:text-xl font-medium text-cream">
                6. Subscriptions, Fees, and Cancellations
              </h2>
              <p>
                Certain features of Klyro are offered under paid subscription plans (such as Pro and Team). When payments become active, fees are billed in advance on a recurring monthly or annual basis as selected during purchase. You may cancel your subscription at any time via your workspace settings.
              </p>
            </section>

            {/* 7. Disclaimers */}
            <section className="space-y-2.5">
              <h2 className="font-serif text-lg sm:text-xl font-medium text-cream">
                7. Disclaimer of Warranties
              </h2>
              <p>
                Klyro and all generated source code are provided on an &ldquo;as is&rdquo; and &ldquo;as available&rdquo; basis without warranties of any kind, either express or implied. While Klyro strives to produce accurate, standards-compliant TypeScript and Next.js code, you are responsible for testing, reviewing, and auditing all generated software before deploying it in live operational environments.
              </p>
            </section>

            {/* 8. Limitation of Liability */}
            <section className="space-y-2.5">
              <h2 className="font-serif text-lg sm:text-xl font-medium text-cream">
                8. Limitation of Liability
              </h2>
              <p>
                In no event shall Klyro, its founders, or affiliates be liable for any indirect, incidental, consequential, special, or punitive damages arising out of or related to your use of the platform or generated code.
              </p>
            </section>

            {/* 9. Contact */}
            <section className="space-y-2.5 rounded-md border border-slate-line bg-ink-raised p-5">
              <h2 className="font-serif text-lg sm:text-xl font-medium text-cream">
                9. Contact Information
              </h2>
              <p>
                For questions regarding these Terms of Service or commercial licensing inquiries, please contact us at:
              </p>
              <p className="font-mono text-xs text-amber mt-2">
                <a href={`mailto:${CONTACT_EMAIL}`} className="hover:underline">
                  {CONTACT_EMAIL}
                </a>
              </p>
            </section>
          </div>
        </div>
      </main>

      <Footer />
    </div>
  );
}
